### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [TORTO21/EtherTechna#3]
Nice Sample State!

### stories and responses
- [ ] instead of `clapIds`, you should reference the user who clapped the story/response, so `clapUserIds` or something like that, because in medium, you can see the list of people who clapped the story/response

### responses
- [ ] `story_id` doesn't have to be null on the third response. Even though you have a `response_id`, you can still have a reference to the `story` for a nested response

**Comment by TORTO21** [comment]
Just a heads up, the clapIds are meant to reference Users, but I didn't put that in semantically.  Sorry about that.  Both items have been addressed, I believe.
